import {type ProjectsProps} from '@/app/contexts'

export const privateProjects: ProjectsProps[] = [
  {
    id: '',
    name: 'TwingBooks',
    fullName: '',
    github: '',
    website: 'https://twinbooks.us/',
    topics: ['javascript', 'nextjs', 'tailwind', 'vercel', 'aws-s3'],
    createdAt: new Date('3/1/2023'),
    madeAt: 'Double2',
  },
  {
    id: '',
    name: 'Lit Data',
    fullName: '',
    github: '',
    website: 'https://www.litdata.org/',
    topics: ['typescript', 'nextjs', 'tailwind', 'sendgrid', 'chartjs'],
    createdAt: new Date('10/1/2023'),
    madeAt: 'MITI MITI ESTUDIO',
  },
  {
    id: '',
    name: 'Global International Imports',
    fullName: '',
    github: '',
    website: 'https://apps.apple.com/us/app/global-international-imports/id6670218504',
    topics: ['typescript', 'react-native', 'expo', 'tailwind', 'sendgrid', 'twilio'],
    createdAt: new Date('4/20/2024'),
    madeAt: 'INITIUM USA CORP',
  },
  {
    id: '',
    name: 'The Dopple',
    fullName: '',
    github: '',
    website: 'https://www.thedopple.com',
    topics: ['typescript', 'nextjs', 'MUI', 'emotion/react'],
    createdAt: new Date('1/7/2021'),
    madeAt: 'Dofleini',
  },
  {
    id: '',
    name: 'Modwell',
    fullName: '',
    github: '',
    website: 'https://www.modwell.io',
    topics: ['javascript', 'nextjs', 'styled-components'],
    createdAt: new Date('1/3/2022'),
    madeAt: 'Dofleini',
  },
  {
    id: '',
    name: 'Ejakí',
    fullName: '',
    github: '',
    website: 'https://www.ejaki.com',
    topics: ['typescript', 'nextjs', 'react', 'emotion/react'],
    createdAt: new Date('1/4/2022'),
    madeAt: 'Dofleini',
  },
  {
    id: '',
    name: 'SmartBarrel',
    fullName: '',
    github: '',
    website: 'https://smartbarrel.io',
    topics: ['javascript', 'nextjs', 'react', 'MUI', 'tailwindcss'],
    createdAt: new Date('1/1/2023'),
    madeAt: 'Double2',
  },
]
