export const reveal = {
  delayBetween: 800,
  distance: '50px',
  duration: 650,
  easing: 'cubic-bezier(0.645, 0.045, 0.355, 1)',
  opacity: 0,
  origin: 'bottom',
  rotate: {
    x: 0,
    y: 0,
    z: 0,
  },
  scale: 1,
  cleanup: false,
  desktop: true,
  mobile: true,
  reset: false,
  useDelay: 'always',
  viewFactor: 0.25,
  viewOffset: {
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
}
